version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Gulp...
      - npm install -g gulp
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on $CODEBUILD_START_TIME
      - echo $CODEBUILD_SRC_DIR
      - echo $CODEBUILD_SRC_DIR_zing
      - ls $CODEBUILD_SRC_DIR_zing
      - ls $CODEBUILD_SRC_DIR_zing/data
      - npm run build
  post_build:
    commands:
      - echo Build ended on $(date -r $CODEBUILD_START_TIME)
# Include only the files required for your application to run.
artifacts:
  files:
    - package.json
    - server.*
    - war/**/*
    - node_modules/**/*
