version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing Gulp...
      - npm install -g gulp
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ls $CODEBUILD_SRC_DIR_zing
      - ls $CODEBUILD_SRC_DIR_zing/Zing
      - ls $CODEBUILD_SRC_DIR_zing/Zing/data
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - server.*
    - war/**/*
